-- MySQL Script generated by MySQL Workbench
-- Fri Jun 24 23:36:51 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema groupomania
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema groupomania
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `groupomania` DEFAULT CHARACTER SET utf8 ;
USE `groupomania` ;

-- -----------------------------------------------------
-- Table `groupomania`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `groupomania`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(55) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `avatar` VARCHAR(150) NULL,
  `firstname` VARCHAR(20) NULL,
  `lastname` VARCHAR(20) NULL,
  `presentation` TEXT NULL,
  `last_seen` TIMESTAMP NULL,
  `has_rights` TINYINT NOT NULL DEFAULT 0,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `groupomania`.`publications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `groupomania`.`publications` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(75) NOT NULL,
  `image` VARCHAR(150) NULL,
  `content` TEXT NULL,
  `created_at` DATETIME NULL,
  `upvote` INT NOT NULL DEFAULT 0,
  `downvote` INT NOT NULL DEFAULT 0,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idpublication_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_publications_users_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_publications_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `groupomania`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `groupomania`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `groupomania`.`comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` TEXT NOT NULL,
  `created_at` DATETIME NULL,
  `publications_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idcomments_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_comments_publications1_idx` (`publications_id` ASC) VISIBLE,
  INDEX `fk_comments_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_comments_publications1`
    FOREIGN KEY (`publications_id`)
    REFERENCES `groupomania`.`publications` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `groupomania`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `groupomania`.`Follows`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `groupomania`.`Follows` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  `followed_id` INT NOT NULL,
  PRIMARY KEY (`id`, `users_id`, `followed_id`),
  INDEX `fk_users_has_users_users2_idx` (`followed_id` ASC) VISIBLE,
  INDEX `fk_users_has_users_users1_idx` (`users_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_users_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `groupomania`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_users_users2`
    FOREIGN KEY (`followed_id`)
    REFERENCES `groupomania`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `groupomania`.`favorites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `groupomania`.`favorites` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `publications_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`, `publications_id`, `users_id`),
  INDEX `fk_publications_has_users_users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_publications_has_users_publications1_idx` (`publications_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_publications_has_users_publications1`
    FOREIGN KEY (`publications_id`)
    REFERENCES `groupomania`.`publications` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_publications_has_users_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `groupomania`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `groupomania`.`publications_votes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `groupomania`.`publications_votes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  `publications_id` INT NOT NULL,
  `value` TINYINT NULL,
  PRIMARY KEY (`id`, `users_id`, `publications_id`),
  INDEX `fk_users_has_publications_publications1_idx` (`publications_id` ASC) VISIBLE,
  INDEX `fk_users_has_publications_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_publications_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `groupomania`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_publications_publications1`
    FOREIGN KEY (`publications_id`)
    REFERENCES `groupomania`.`publications` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO users(username,email,password,has_rights)VALUES('Admin','admin@groupomania.fr','Groupomania1',1);